"""removed condition for confirm password

Revision ID: 29e2cff797a6
Revises: d42e05f78417
Create Date: 2026-02-12 17:01:31.746913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e2cff797a6'
down_revision: Union[str, Sequence[str], None] = 'd42e05f78417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'confirm_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'confirm_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
