"""update_booking_model

Revision ID: 4273a52d5a08
Revises: 47f2aaf083d2
Create Date: 2026-02-13 00:22:42.979178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4273a52d5a08'
down_revision: Union[str, Sequence[str], None] = '47f2aaf083d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('booking', 'booking_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint('unique_user_event_booking', 'booking', ['user_id', 'event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_event_booking', 'booking', type_='unique')
    op.alter_column('booking', 'booking_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('booking', 'status')
    # ### end Alembic commands ###
