"""change_role_to_enum

Revision ID: 47f2aaf083d2
Revises: 872db4e17d61
Create Date: 2026-02-13 00:11:44.087659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f2aaf083d2'
down_revision: Union[str, Sequence[str], None] = '872db4e17d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the Enum type manually first
    role_enum = sa.Enum('organizer', 'attendee', 'admin', name='role_enum')
    role_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               type_=role_enum,
               existing_nullable=False,
               postgresql_using="role::role_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.Enum('organizer', 'attendee', 'admin', name='role_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
    
    # Drop the Enum type manually
    role_enum = sa.Enum('organizer', 'attendee', 'admin', name='role_enum')
    role_enum.drop(op.get_bind(), checkfirst=True)
