"""remove_confirm_password_from_user

Revision ID: 872db4e17d61
Revises: c8e199881203
Create Date: 2026-02-12 21:08:29.919024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872db4e17d61'
down_revision: Union[str, Sequence[str], None] = 'c8e199881203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirm_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirm_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
