"""Add cascading deletes

Revision ID: c1d319a7d794
Revises: 4273a52d5a08
Create Date: 2026-02-20 14:24:05.326294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d319a7d794'
down_revision: Union[str, Sequence[str], None] = '4273a52d5a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('booking_user_id_fkey'), 'booking', type_='foreignkey')
    op.drop_constraint(op.f('booking_event_id_fkey'), 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'booking', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('event_organizer_id_fkey'), 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'user', ['organizer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key(op.f('event_organizer_id_fkey'), 'event', 'user', ['organizer_id'], ['id'])
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key(op.f('booking_event_id_fkey'), 'booking', 'event', ['event_id'], ['id'])
    op.create_foreign_key(op.f('booking_user_id_fkey'), 'booking', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
