"""add_capacity_to_event

Revision ID: c8e199881203
Revises: 5eec7a76f143
Create Date: 2026-02-12 19:08:16.938330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e199881203'
down_revision: Union[str, Sequence[str], None] = '5eec7a76f143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('capacity', sa.Integer(), nullable=False))
    op.add_column('event', sa.Column('booked_seats', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'booked_seats')
    op.drop_column('event', 'capacity')
    # ### end Alembic commands ###
