"""change_role_to_string

Revision ID: fe4dc8970019
Revises: 4a530dfaef54
Create Date: 2026-02-11 22:29:46.759087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe4dc8970019'
down_revision: Union[str, Sequence[str], None] = '4a530dfaef54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('ORGANIZER', 'ATTENDEE', 'SUPER_ADMIN', name='role'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('ORGANIZER', 'ATTENDEE', 'SUPER_ADMIN', name='role'),
               existing_nullable=False)
    # ### end Alembic commands ###
